# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 548e1d8783cfe22426ce1c512ea82305c37d4bcc794b86353449cb8b8fc1def98b86c7aac10b041818a74d500d41d9f403afd07128eee62084b9d2c22a7f8545

test:
  secret_key_base: c02d263498afdf08fcf6c523e4ef4562f252fee09f8d2daf093df1ee3d58ad09047e6df1f567f2cc2e405e560d7769e7b2dcac03862395c41d208cc5354666f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
